var currentWeekNumber = require('current-week-number');
var moment = require('moment');
let startOfWeek, endOfWeek;
var today = moment('2017-01-15').toDate();
console.log(today);
startOfWeek = moment().startOf('month').add(1,'days').toDate();
endOfWeek   = moment(today).endOf('week').toDate();
console.log(startOfWeek);
console.log(endOfWeek);
console.log(currentWeekNumber(startOfWeek));
console.log(currentWeekNumber(endOfWeek));
console.log(moment(endOfWeek).subtract(6, 'days').toDate());
console.log(moment(startOfWeek).subtract(6, 'days').toDate());
console.log(currentWeekNumber(moment(endOfWeek).subtract(6, 'days').toDate()));
console.log(currentWeekNumber(moment(startOfWeek).subtract(6, 'days').toDate()));
